### ISSUE TITLE
ctrl-b consumed by extension without intimation in readme

### ISSUE THREAD

**Issue by goyalyashpal** [AnWeber/vscode-swapf#3]
Type: <b>Bug</b>

* Press ctrl-b in a `__main__.py` or `__init__.py` file from src dir in a workspace containing a `.venv`

expected: primary side bar is toggled
actual: it swaps between the current file and some file from .venv of same name

Extension version: 1.6.1
VSCodium version: VSCodium 1.87.1 (8ef912c5ff083dd372870b5140c487802774d1ed, 2024-03-08T18:32:33.565Z)
OS version: Windows_NT x64 10.0.19045
Modes:

**Comment by AnWeber** [comment]
@goyalyashpal It is already documented if you install the extension in vscode. There is a Tab to view all commands and keybindings. I find it redundant to document this in other places. No other extensions do this either. But hey, I add it in the readme.
<img width="1092" alt="image" src="https://github.com/AnWeber/vscode-swapf/assets/13434739/1f4284bc-38d7-4fa1-a715-5f5242953730">

I probably have to apologize for the fact that you were looking for longer. As a tip, you can search for the shortcut in the [keybindings in VSCode](https://code.visualstudio.com/docs/getstarted/keybindings) to see which extensions react to it.

**Comment by goyalyashpal** [comment]
holly molly, so i missed it at 2 places. oops.

but yeah, these 3 points below caused such behaviour of mine:
* i had not changed anything regarding this extension ever since i installed it
* and ever since the shortcut `C-b` was working usual - for toggling primary side bar
* and today suddenly it started opening those files


so i just ran `extension bisect` in vscodium and followed the instructions... it asked "file bug report?", and i proceeded to it without much thinking
